//! Machine-consumed contract manifest (`tests/contracts.json`): an
//! exhaustive inventory of the Go reference surface — routes, YAML keys,
//! auxiliary commands/flags, platform assets and every `*_test.go` case —
//! each mapped to the Rust test target and owning plan task.
//!
//! The manifest is generated by scanning G (`qa manifest`), never edited by
//! hand; `verify_coverage` re-scans G and fails on any drift in either
//! direction, which is what makes "exhaustive" checkable.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Route {
    pub method: String,
    pub path: String,
    /// `file:line` in the Go tree.
    pub source: String,
    pub owner_task: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfigKey {
    /// Dotted YAML path, e.g. `devin.gate_max_hold_seconds`.
    pub key: String,
    pub source: String,
    pub owner_task: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuxCommand {
    pub binary: String,
    /// Subcommand or flag name (`-listen` stored as `listen`).
    pub name: String,
    /// `subcommand` | `flag` | `positional`.
    pub kind: String,
    pub detail: String,
    pub owner_task: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Asset {
    pub path: String,
    /// script | workflow | action | docker | e2e | doc | schema | config | meta.
    pub kind: String,
    pub owner_task: u8,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GoCase {
    /// Go test file relative to G, e.g. `internal/app/app_test.go`.
    pub file: String,
    /// Function name, e.g. `TestHealthz`.
    pub function: String,
    /// test | benchmark | example | fuzz.
    pub kind: String,
    /// Exact executable Rust check id: `<integration-target>::<test-name>`.
    /// Task 23 resolves this against `cargo test -- --list` and executes the
    /// containing target before crediting the case.
    pub rust_case: String,
    /// `rust_test` or `intentional_deviation`.
    pub disposition: String,
    /// Required for intentional deviations; empty for executable suites.
    pub reason: String,
    pub owner_task: u8,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Manifest {
    pub schema: u32,
    pub generated_by: String,
    /// Actual `git rev-parse HEAD` of the scanned Go tree.
    pub go_commit: String,
    pub routes: Vec<Route>,
    pub config_keys: Vec<ConfigKey>,
    pub aux_commands: Vec<AuxCommand>,
    pub platform_assets: Vec<Asset>,
    pub go_test_cases: Vec<GoCase>,
}

/// Go test file → (Rust integration target, owning plan task).
/// Every `*_test.go` in G must appear here or the scan fails — a new Go
/// test file can never silently fall out of the manifest.
fn go_test_file_map(file: &str) -> Option<(&'static str, u8)> {
    Some(match file {
        "cmd/devin-2api/main_test.go" => ("lifecycle", 19),
        "cmd/protoextract/main_test.go" => ("auxiliary_cli", 20),
        "internal/adapter/devin/bench_perf_test.go"
        | "internal/api/common/bench_perf_test.go"
        | "internal/api/openai/chat/bench_perf_test.go"
        | "internal/api/openai/responses/bench_perf_test.go"
        | "internal/app/bench_perf_test.go" => ("benchmark_verdict", 24),
        "internal/adapter/devin/devin_test.go" => ("upstream_lifecycle", 11),
        "internal/adapter/devin/rategate_test.go" => ("rate_gate", 10),
        "internal/adapter/devin/replay_test.go" => ("response_decoder", 9),
        "internal/adapter/devin/sanitize_test.go"
        | "internal/adapter/devin/tool_definition_test.go" => ("request_projection", 8),
        "internal/api/anthropic/messages/request_test.go"
        | "internal/api/common/toolchoice_test.go"
        | "internal/api/openai/chat/request_test.go"
        | "internal/api/openai/responses/request_test.go"
        | "internal/llm/failure_test.go"
        | "internal/llm/request_test.go"
        | "internal/llm/response_test.go" => ("input_protocols", 5),
        "internal/api/anthropic/messages/response_test.go"
        | "internal/api/common/error_test.go"
        | "internal/api/openai/chat/response_test.go"
        | "internal/api/openai/responses/response_test.go" => ("output_protocols", 12),
        "internal/app/app_anthropic_test.go"
        | "internal/app/app_chat_test.go"
        | "internal/app/app_test.go" => ("http_surface", 14),
        "internal/app/app_websocket_test.go" => ("websocket_surface", 15),
        "internal/config/config_test.go" => ("config_contract", 4),
        "internal/dashboard/handler_test.go"
        | "internal/dashboard/helpers_test.go"
        | "internal/dashboard/merge_test.go"
        | "internal/dashboard/quota_test.go" => ("dashboard_api", 17),
        "internal/debuglog/index_test.go"
        | "internal/debuglog/recorder_test.go"
        | "internal/debuglog/usage_test.go" => ("debuglog_compat", 13),
        "internal/obs/metrics_test.go" => ("diagnostics", 16),
        "internal/upstream/upstream_test.go" => ("transport_interop", 6),
        _ => return None,
    })
}

/// Scan the Go reference tree and build the manifest.
pub fn scan_go_reference(go_root: &Path) -> anyhow::Result<Manifest> {
    let mut manifest = Manifest {
        schema: 3,
        generated_by: "qa manifest (task 2 contracts scanner)".into(),
        go_commit: git_head(go_root).unwrap_or_else(|_| "unknown".into()),
        routes: scan_routes(go_root)?,
        config_keys: scan_config_keys(go_root)?,
        aux_commands: scan_aux_commands(go_root)?,
        platform_assets: scan_assets(go_root),
        go_test_cases: scan_go_tests(go_root)?,
    };
    manifest
        .routes
        .sort_by(|a, b| (&a.path, &a.method).cmp(&(&b.path, &b.method)));
    manifest.config_keys.sort_by(|a, b| a.key.cmp(&b.key));
    manifest
        .aux_commands
        .sort_by(|a, b| (&a.binary, &a.kind, &a.name).cmp(&(&b.binary, &b.kind, &b.name)));
    manifest.platform_assets.sort_by(|a, b| a.path.cmp(&b.path));
    manifest
        .go_test_cases
        .sort_by(|a, b| (&a.file, &a.function).cmp(&(&b.file, &b.function)));
    Ok(manifest)
}

/// Load the committed manifest from `tests/contracts.json`.
pub fn load_committed() -> anyhow::Result<Manifest> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/contracts.json");
    let raw = std::fs::read_to_string(&path)
        .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;
    Ok(serde_json::from_str(&raw)?)
}

/// Re-scan G and verify the manifest covers it exactly. Returns a list of
/// problems; empty means the manifest is exhaustive and current.
pub fn verify_coverage(manifest: &Manifest, go_root: &Path) -> anyhow::Result<Vec<String>> {
    let mut problems = Vec::new();
    let actual = scan_go_reference(go_root)?;

    let want: BTreeMap<(&str, &str), &GoCase> = manifest
        .go_test_cases
        .iter()
        .map(|c| ((c.file.as_str(), c.function.as_str()), c))
        .collect();
    let have: BTreeMap<(&str, &str), &GoCase> = actual
        .go_test_cases
        .iter()
        .map(|c| ((c.file.as_str(), c.function.as_str()), c))
        .collect();
    for key in have.keys() {
        if !want.contains_key(key) {
            problems.push(format!("unmapped Go test case {}::{}", key.0, key.1));
        }
    }
    for key in want.keys() {
        if !have.contains_key(key) {
            problems.push(format!("stale manifest case {}::{}", key.0, key.1));
        }
    }
    for case in &manifest.go_test_cases {
        match case.disposition.as_str() {
            "rust_test" => {
                let Some((target, test)) = case.rust_case.split_once("::") else {
                    problems.push(format!(
                        "case {}::{} has invalid Rust check id {:?}",
                        case.file, case.function, case.rust_case
                    ));
                    continue;
                };
                let target_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                    .join("tests")
                    .join(format!("{target}.rs"));
                if target.is_empty() || test.is_empty() || !target_path.is_file() {
                    problems.push(format!(
                        "case {}::{} maps to invalid Rust check {}",
                        case.file, case.function, case.rust_case
                    ));
                }
                if !case.reason.is_empty() {
                    problems.push(format!(
                        "executable case {}::{} unexpectedly has a deviation reason",
                        case.file, case.function
                    ));
                }
            }
            "intentional_deviation" => {
                if case.kind != "benchmark" || case.owner_task != 24 || case.reason.is_empty() {
                    problems.push(format!(
                        "case {}::{} has an unapproved intentional deviation",
                        case.file, case.function
                    ));
                }
                if !case.rust_case.is_empty() {
                    problems.push(format!(
                        "deviation {}::{} must not claim an executable Rust id",
                        case.file, case.function
                    ));
                }
            }
            other => problems.push(format!(
                "case {}::{} has unknown disposition {other:?}",
                case.file, case.function
            )),
        }
        if case.owner_task == 0 {
            problems.push(format!(
                "case {}::{} lacks owner_task",
                case.file, case.function
            ));
        }
    }

    let (wr, hr) = (route_set(&manifest.routes), route_set(&actual.routes));
    for key in hr.keys() {
        if !wr.contains_key(key) {
            problems.push(format!("unmapped route {} {}", key.0, key.1));
        }
    }
    for key in wr.keys() {
        if !hr.contains_key(key) {
            problems.push(format!("stale route {} {}", key.0, key.1));
        }
    }

    let (wk, hk) = (key_set(&manifest.config_keys), key_set(&actual.config_keys));
    for key in hk.keys() {
        if !wk.contains_key(key) {
            problems.push(format!("unmapped config key {key}"));
        }
    }
    for key in wk.keys() {
        if !hk.contains_key(key) {
            problems.push(format!("stale config key {key}"));
        }
    }
    Ok(problems)
}

fn route_set(routes: &[Route]) -> BTreeMap<(String, String), &Route> {
    routes
        .iter()
        .map(|r| ((r.method.clone(), r.path.clone()), r))
        .collect()
}

fn key_set(keys: &[ConfigKey]) -> BTreeMap<&str, &ConfigKey> {
    keys.iter().map(|k| (k.key.as_str(), k)).collect()
}

fn git_head(go_root: &Path) -> anyhow::Result<String> {
    let out = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(go_root)
        .output()?;
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

// --- routes ---------------------------------------------------------------

/// Chi-style registrations `.Get("/path", ...)` / `.Post(...)` in the app
/// and dashboard sources.
fn scan_routes(go_root: &Path) -> anyhow::Result<Vec<Route>> {
    const SOURCES: &[(&str, u8)] = &[
        ("internal/app/app.go", 14),
        ("internal/dashboard/handler.go", 17),
    ];
    const METHODS: &[&str] = &["Get", "Post", "Put", "Delete", "Patch", "Head", "Options"];
    let mut routes = Vec::new();
    for (file, owner) in SOURCES {
        let path = go_root.join(file);
        let text = std::fs::read_to_string(&path)
            .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;
        for (lineno, line) in text.lines().enumerate() {
            for method in METHODS {
                let needle = format!(".{method}(\"");
                let mut search = line;
                while let Some(idx) = search.find(&needle) {
                    // Receiver must be a chi-style router identifier, not
                    // e.g. `r.Header.Get("Accept")`.
                    const ROUTERS: &[&str] = &[
                        "router",
                        "protected",
                        "ws",
                        "gated",
                        "mux",
                        "r",
                        "api",
                        "panel",
                    ];
                    let before = &search[..idx];
                    let receiver: String = before
                        .chars()
                        .rev()
                        .take_while(|c| c.is_alphanumeric() || *c == '_')
                        .collect::<String>()
                        .chars()
                        .rev()
                        .collect();
                    if !ROUTERS.contains(&receiver.as_str()) {
                        search = &search[idx + needle.len()..];
                        continue;
                    }
                    let rest = &search[idx + needle.len()..];
                    if let Some(end) = rest.find('"') {
                        let route_path = &rest[..end];
                        let owner = if *method == "Get" && route_path == "/v1/responses" {
                            15 // Responses WebSocket upgrade route.
                        } else {
                            *owner
                        };
                        routes.push(Route {
                            method: method.to_uppercase(),
                            path: route_path.to_string(),
                            source: format!("{file}:{}", lineno + 1),
                            owner_task: owner,
                        });
                        search = &rest[end + 1..];
                    } else {
                        break;
                    }
                }
            }
        }
    }
    Ok(routes)
}

// --- config keys ----------------------------------------------------------

/// Parse `internal/config/config.go`: struct yaml tags resolved through the
/// top-level Config sections into dotted keys.
fn scan_config_keys(go_root: &Path) -> anyhow::Result<Vec<ConfigKey>> {
    let path = go_root.join("internal/config/config.go");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))?;

    // Pass 1: struct name → [(yaml key, line)].
    let mut structs: BTreeMap<String, Vec<(String, usize)>> = BTreeMap::new();
    // Pass 2 prep: Config struct field type → yaml section.
    let mut section_types: BTreeMap<String, String> = BTreeMap::new();
    let mut current: Option<String> = None;
    let mut in_config = false;
    for (lineno, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.starts_with("type ") && trimmed.ends_with(" struct {") {
            let name = trimmed
                .trim_start_matches("type ")
                .trim_end_matches(" struct {")
                .trim()
                .to_string();
            in_config = name == "Config";
            current = Some(name);
            continue;
        }
        if trimmed == "}" {
            current = None;
            in_config = false;
            continue;
        }
        let Some(struct_name) = &current else {
            continue;
        };
        let Some(yaml_key) = extract_yaml_key(trimmed) else {
            continue;
        };
        structs
            .entry(struct_name.clone())
            .or_default()
            .push((yaml_key.clone(), lineno + 1));
        if in_config {
            // `Server ServerConfig `yaml:"server"`` → ServerConfig under "server".
            let field_type = trimmed
                .split_whitespace()
                .nth(1)
                .unwrap_or("")
                .trim_start_matches('*')
                .to_string();
            section_types.insert(field_type, yaml_key);
        }
    }

    let mut keys = Vec::new();
    for (type_name, section) in &section_types {
        if let Some(fields) = structs.get(type_name) {
            for (key, line) in fields {
                keys.push(ConfigKey {
                    key: format!("{section}.{key}"),
                    source: format!("internal/config/config.go:{line}"),
                    owner_task: 4,
                });
            }
        }
    }
    Ok(keys)
}

/// `Token string` with tag `yaml:"token"` → `token`; `yaml:"-"` and
/// missing tags → None.
fn extract_yaml_key(line: &str) -> Option<String> {
    let start = line.find("yaml:\"")? + 6;
    let rest = &line[start..];
    let end = rest.find('"')?;
    let key = &rest[..end];
    if key.is_empty() || key == "-" {
        return None;
    }
    Some(key.to_string())
}

// --- auxiliary commands ---------------------------------------------------

fn scan_aux_commands(go_root: &Path) -> anyhow::Result<Vec<AuxCommand>> {
    let mut out = Vec::new();

    // devin-2api: top-level flag.* registrations in cmd/devin-2api/main.go.
    for flag in scan_flag_calls(&read(go_root, "cmd/devin-2api/main.go")?) {
        out.push(AuxCommand {
            binary: "devin-2api".into(),
            name: flag,
            kind: "flag".into(),
            detail: "cmd/devin-2api/main.go".into(),
            owner_task: 19,
        });
    }

    // probe: subcommands from the `commands` map, flags per FlagSet,
    // edge-case names from the cmdEdge switch.
    let probe = read(go_root, "cmd/probe/main.go")?;
    for name in scan_map_keys(&probe, "var commands = map[") {
        out.push(AuxCommand {
            binary: "probe".into(),
            name,
            kind: "subcommand".into(),
            detail: "cmd/probe/main.go commands map".into(),
            owner_task: 20,
        });
    }
    for (set, flag) in scan_flagsets(&probe) {
        out.push(AuxCommand {
            binary: "probe".into(),
            name: flag,
            kind: "flag".into(),
            detail: format!("probe {set}"),
            owner_task: 20,
        });
    }
    for case in scan_func_cases(&probe, "func cmdEdge") {
        out.push(AuxCommand {
            binary: "probe".into(),
            name: case,
            kind: "subcommand".into(),
            detail: "probe edge case".into(),
            owner_task: 20,
        });
    }

    // protocensus: `case "census":` / `case "diff":` in the os.Args switch.
    let census = read(go_root, "cmd/protocensus/main.go")?;
    for name in scan_args_switch(&census) {
        out.push(AuxCommand {
            binary: "protocensus".into(),
            name,
            kind: "subcommand".into(),
            detail: "cmd/protocensus/main.go".into(),
            owner_task: 20,
        });
    }
    for (set, flag) in scan_flagsets(&census) {
        out.push(AuxCommand {
            binary: "protocensus".into(),
            name: flag,
            kind: "flag".into(),
            detail: format!("protocensus {set}"),
            owner_task: 20,
        });
    }

    // loadtest / upstreamstub: flat flag.* registrations.
    for binary in ["loadtest", "upstreamstub"] {
        let text = read(go_root, &format!("cmd/{binary}/main.go"))?;
        for flag in scan_flag_calls(&text) {
            out.push(AuxCommand {
                binary: binary.into(),
                name: flag,
                kind: "flag".into(),
                detail: format!("cmd/{binary}/main.go"),
                owner_task: 20,
            });
        }
    }

    // protoextract: positional <source-binary> <output-directory>.
    out.push(AuxCommand {
        binary: "protoextract".into(),
        name: "extract".into(),
        kind: "positional".into(),
        detail: "protoextract <source-binary> <output-directory>".into(),
        owner_task: 20,
    });
    Ok(out)
}

fn read(go_root: &Path, rel: &str) -> anyhow::Result<String> {
    let path = go_root.join(rel);
    std::fs::read_to_string(&path).map_err(|e| anyhow::anyhow!("read {}: {e}", path.display()))
}

/// `flag.String("name", ...)` / `flag.Int(` etc. → flag names.
fn scan_flag_calls(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        for func in [
            "String", "Int", "Bool", "Duration", "Float64", "Int64", "Uint",
        ] {
            let needle = format!("flag.{func}(\"");
            if let Some(idx) = line.find(&needle) {
                let rest = &line[idx + needle.len()..];
                if let Some(end) = rest.find('"') {
                    out.push(rest[..end].to_string());
                }
            }
        }
    }
    out
}

/// `fs := flag.NewFlagSet("name", ...)` then `fs.Xxx("flag", ...)` until the
/// next `FlagSet` — returns (flagset, flag) pairs.
fn scan_flagsets(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<String> = None;
    for line in text.lines() {
        let line = line.trim();
        if let Some(idx) = line.find("flag.NewFlagSet(\"") {
            let rest = &line[idx + 16..];
            if let Some(end) = rest.find('"') {
                current = Some(rest[..end].to_string());
            }
            continue;
        }
        if line.starts_with("func ") {
            current = None;
            continue;
        }
        let Some(set) = &current else { continue };
        if line.starts_with("fs.") || line.starts_with("flag.") {
            for func in [
                "String", "Int", "Bool", "Duration", "Float64", "Int64", "Uint", "Var",
            ] {
                let needle = format!(".{func}(\"");
                if let Some(idx) = line.find(&needle) {
                    let rest = &line[idx + needle.len()..];
                    if let Some(end) = rest.find('"') {
                        out.push((set.clone(), rest[..end].to_string()));
                    }
                }
            }
        }
    }
    out
}

/// `"name": cmdXxx,` entries inside a `var X = map[` literal.
fn scan_map_keys(text: &str, marker: &str) -> Vec<String> {
    let mut out = Vec::new();
    let Some(start) = text.find(marker) else {
        return out;
    };
    let rest = &text[start..];
    let Some(end) = rest.find("\n}") else {
        return out;
    };
    for line in rest[..end].lines() {
        let line = line.trim();
        if let Some(stripped) = line.strip_prefix('"')
            && let Some(end) = stripped.find('"')
        {
            out.push(stripped[..end].to_string());
        }
    }
    out
}

/// `case "name":` lines inside the `switch os.Args[1]` dispatch.
fn scan_args_switch(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let Some(start) = text.find("switch os.Args[1]") else {
        return out;
    };
    let rest = &text[start..];
    let Some(end) = rest.find("\n}") else {
        return out;
    };
    for line in rest[..end].lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("case \"")
            && let Some(end) = rest.find('"')
        {
            out.push(rest[..end].to_string());
        }
    }
    out
}

/// `case "name":` lines inside one function body (e.g. `cmdEdge`).
fn scan_func_cases(text: &str, func_marker: &str) -> Vec<String> {
    let mut out = Vec::new();
    let Some(start) = text.find(func_marker) else {
        return out;
    };
    let rest = &text[start..];
    // Function body ends at the next top-level `func `.
    let end = rest[1..].find("\nfunc ").map_or(rest.len(), |i| i + 1);
    for line in rest[..end].lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("case \"")
            && let Some(end) = rest.find('"')
        {
            out.push(rest[..end].to_string());
        }
    }
    out
}

// --- platform assets --------------------------------------------------------

fn scan_assets(go_root: &Path) -> Vec<Asset> {
    let mut out = Vec::new();
    let mut add = |path: &str, kind: &str, owner: u8| {
        if go_root.join(path).exists() {
            out.push(Asset {
                path: path.to_string(),
                kind: kind.to_string(),
                owner_task: owner,
            });
        }
    };
    // Fixed singletons.
    for (path, kind, owner) in [
        ("Taskfile.yml", "meta", 3u8),
        ("go.mod", "meta", 1),
        ("go.sum", "meta", 1),
        ("LICENSE", "meta", 1),
        ("config.example.yaml", "config", 4),
        ("Dockerfile", "docker", 21),
        ("Dockerfile.release", "docker", 21),
        ("README.md", "doc", 25),
        ("README.zh-CN.md", "doc", 25),
        ("AGENTS.md", "doc", 25),
    ] {
        add(path, kind, owner);
    }
    // Directory walks.
    for (dir, kind, owner) in [
        ("scripts", "script", 21u8),
        (".github/workflows", "workflow", 22),
        (".github/actions", "action", 22),
        ("e2e", "e2e", 20),
        ("docs", "doc", 25),
        ("outputs/devin-proto", "schema", 3),
    ] {
        let root = go_root.join(dir);
        if root.is_dir() {
            walk(&root, go_root, &mut |rel| {
                out.push(Asset {
                    path: rel,
                    kind: kind.to_string(),
                    owner_task: owner,
                });
            });
        }
    }
    out
}

fn walk(dir: &Path, root: &Path, emit: &mut dyn FnMut(String)) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, root, emit);
        } else if let Ok(rel) = path.strip_prefix(root) {
            emit(rel.display().to_string());
        }
    }
}

// --- go test cases ----------------------------------------------------------

fn scan_go_tests(go_root: &Path) -> anyhow::Result<Vec<GoCase>> {
    let binding_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/contract-bindings.json");
    let binding_doc: serde_json::Value = serde_json::from_slice(&std::fs::read(&binding_path)?)?;
    let bindings = binding_doc["bindings"]
        .as_object()
        .ok_or_else(|| anyhow::anyhow!("{} lacks bindings object", binding_path.display()))?;
    let mut out = Vec::new();
    let mut files = Vec::new();
    collect_test_files(go_root, go_root, &mut files);
    files.sort();
    for rel in files {
        let Some((_target, owner)) = go_test_file_map(&rel) else {
            anyhow::bail!("unmapped Go test file {rel}: add it to go_test_file_map");
        };
        let text = read(go_root, &rel)?;
        for line in text.lines() {
            if let Some((kind, name)) = parse_test_func(line) {
                let benchmark = kind == "benchmark";
                let binding_key = format!("{rel}::{name}");
                let rust_case = if benchmark {
                    String::new()
                } else {
                    bindings
                        .get(&binding_key)
                        .and_then(|binding| binding["rust_case"].as_str())
                        .ok_or_else(|| {
                            anyhow::anyhow!(
                                "functional Go case {binding_key} lacks an exact entry in {}",
                                binding_path.display()
                            )
                        })?
                        .to_string()
                };
                out.push(GoCase {
                    file: rel.clone(),
                    rust_case,
                    function: name,
                    kind,
                    disposition: if benchmark {
                        "intentional_deviation".into()
                    } else {
                        "rust_test".into()
                    },
                    reason: if benchmark {
                        "Performance-only Go benchmark; executable paired Rust/Go benchmark coverage is owned by task 24 and is not a functional parity assertion.".into()
                    } else {
                        String::new()
                    },
                    owner_task: owner,
                });
            }
        }
    }
    Ok(out)
}

fn collect_test_files(dir: &Path, root: &Path, out: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        // Never descend into .git or generated module dirs.
        if path.is_dir() {
            let name = entry.file_name();
            if name != ".git" && name != "vendor" {
                collect_test_files(&path, root, out);
            }
        } else if entry.file_name().to_string_lossy().ends_with("_test.go")
            && let Ok(rel) = path.strip_prefix(root)
        {
            out.push(rel.display().to_string());
        }
    }
}

/// `func TestXxx(t *testing.T) {` → (test, Xxx); also Benchmark/Example/Fuzz.
fn parse_test_func(line: &str) -> Option<(String, String)> {
    let line = line.trim_start();
    for (prefix, kind) in [
        ("func Test", "test"),
        ("func Benchmark", "benchmark"),
        ("func Example", "example"),
        ("func Fuzz", "fuzz"),
    ] {
        if let Some(rest) = line.strip_prefix(prefix) {
            let end = rest.find('(')?;
            let name = &rest[..end];
            if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                return Some((kind.to_string(), name.to_string()));
            }
        }
    }
    None
}
