//! Output-protocol contract tests for the devin2api Rust port (plan task 12).
//!
//! Ports `G/internal/api/{`openai`/responses,`openai`/chat,anthropic/messages}/response_test.go`
//! and `G/internal/api/common/error_test.go` against
//! `devin2api::protocol::{responses,chat,messages,common,dispatch}`. Test
//! names map to the `rust_case` entries in `tests/contracts.json`
//! (`owner_task` 12); each test notes its Go source.
//!
//! `Stream`/final/error bodies are compared against `fixtures/task12/
//! expected.json`, generated by replaying `cases.json` through the Go
//! encoders (see `go-oracle/internal/app/fixture_oracle_test.go` in the
//! task-12 evidence dir). Generated ids (`resp_*`, `msg_*`, `rs_*`, `fc_*`,
//! `chatcmpl-*`) and wall-clock timestamps canonicalize through
//! `qa::compare` — distinct ids map to `<id#N>` per case, so cross-event id
//! consistency (delta `item_id` == added `item.id`, completed `response.id`
//! == created `response.id`) is still asserted.

use std::sync::Arc;

use serde::Deserialize;
use serde_json::{Value, json};

use devin2api::domain::{
    AssistantMessage, Content, Failure, ResponseEvent, ResponseEventType, StopReason, TextContent,
    ThinkingContent, ToolCall, Usage,
};
use devin2api::protocol::common::{
    self, SseEvent, anthropic_error_type, error_code, http_status, openai_error_type,
};
use devin2api::protocol::dispatch::{
    self, AnthropicProtocol, ChatProtocol, HttpError, ProtocolEncoder, ResponsesProtocol,
};
use devin2api::qa::compare::{CanonRules, canonicalize_json};

// ---------------------------------------------------------------------------
// Fixture schema (mirrors the Go oracle harness)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureContent {
    kind: String,
    #[serde(default)]
    text: String,
    #[serde(default)]
    thinking: String,
    #[serde(default)]
    signature: String,
    #[serde(default)]
    signature_type: String,
    #[serde(default)]
    redacted: bool,
    #[serde(default)]
    tool_call: Option<FixtureToolCall>,
}

#[derive(Debug, Deserialize)]
struct FixtureToolCall {
    id: String,
    name: String,
    arguments: String,
    #[serde(default)]
    custom: bool,
}

#[derive(Debug, Deserialize)]
struct FixtureUsage {
    input: i64,
    output: i64,
    cache_read: i64,
    cache_write: i64,
    total_tokens: i64,
    reasoning: Option<i64>,
}

#[derive(Debug, Deserialize)]
struct FixtureMessage {
    #[serde(default)]
    content: Vec<FixtureContent>,
    #[serde(default)]
    api: String,
    #[serde(default)]
    provider: String,
    #[serde(default)]
    model: String,
    #[serde(default)]
    response_model: String,
    #[serde(default)]
    response_id: String,
    #[serde(default)]
    output_id: String,
    #[serde(default)]
    upstream_request_id: String,
    #[serde(default)]
    usage: Option<FixtureUsage>,
    #[serde(default)]
    stop_reason: String,
    #[serde(default)]
    stop_sequence: String,
    #[serde(default)]
    error_message: String,
    #[serde(default)]
    debug_ref: String,
    #[serde(default)]
    timestamp_ms: i64,
}

#[derive(Debug, Deserialize)]
struct FixtureEvent {
    #[serde(rename = "type")]
    kind: String,
    #[serde(default)]
    content_index: i32,
    #[serde(default)]
    delta: String,
    #[serde(default)]
    content: String,
    #[serde(default)]
    partial: Option<FixtureMessage>,
    #[serde(default)]
    tool_call_id: String,
    #[serde(default)]
    tool_name: String,
    #[serde(default)]
    tool_call: Option<FixtureToolCall>,
    #[serde(default)]
    reason: String,
    #[serde(default)]
    message: Option<FixtureMessage>,
    #[serde(default)]
    error: Option<FixtureMessage>,
}

/// Mirrors Go's `llm.Failure` field-for-field; the bool set is the wire
/// schema, not a state machine.
#[derive(Debug, Deserialize)]
#[allow(clippy::struct_excessive_bools)]
struct FixtureFailure {
    #[serde(default)]
    code: String,
    #[serde(default)]
    message: String,
    #[serde(default)]
    local_gate: bool,
    #[serde(default)]
    upstream_fault: bool,
    #[serde(default)]
    retry_after_seconds: i64,
    #[serde(default)]
    retry_after_minute: bool,
    #[serde(default)]
    context_length: bool,
    #[serde(default)]
    rate_limited: bool,
    #[serde(default)]
    canceled: bool,
    #[serde(default)]
    timeout: bool,
    #[serde(default)]
    client_fixable: bool,
    #[serde(default)]
    trace_id: String,
    #[serde(default)]
    reset_hint: bool,
}

#[derive(Debug, Deserialize)]
struct FixtureHttpError {
    failure: FixtureFailure,
    #[serde(default)]
    client_fixable: bool,
    #[serde(default)]
    stage: String,
    #[serde(default)]
    debug_ref: String,
}

#[derive(Debug, Deserialize)]
struct FixtureCase {
    name: String,
    protocol: String,
    mode: String,
    #[serde(default)]
    model: String,
    #[serde(default)]
    include_usage: bool,
    #[serde(default)]
    events: Vec<FixtureEvent>,
    #[serde(default)]
    message: Option<FixtureMessage>,
    #[serde(default)]
    error: Option<FixtureFailure>,
    #[serde(default)]
    debug_ref: String,
    #[serde(default)]
    http_error: Option<FixtureHttpError>,
}

#[derive(Debug, Deserialize)]
struct ExpectedSse {
    name: String,
    data: String,
}

#[derive(Debug, Deserialize)]
struct ExpectedCase {
    name: String,
    #[serde(default)]
    sse: Vec<ExpectedSse>,
    #[serde(default)]
    json: Option<String>,
    #[serde(default)]
    encode_error: Option<String>,
}

#[derive(Debug, Deserialize)]
struct FixtureFile<T> {
    cases: Vec<T>,
}

fn load_cases() -> Vec<FixtureCase> {
    let data = include_str!("fixtures/task12/cases.json");
    serde_json::from_str::<FixtureFile<FixtureCase>>(data)
        .expect("cases.json parses")
        .cases
}

fn load_expected() -> Vec<ExpectedCase> {
    let data = include_str!("fixtures/task12/expected.json");
    serde_json::from_str::<FixtureFile<ExpectedCase>>(data)
        .expect("expected.json parses")
        .cases
}

// ---------------------------------------------------------------------------
// Fixture -> domain conversion
// ---------------------------------------------------------------------------

fn to_content(content: &FixtureContent) -> Content {
    match content.kind.as_str() {
        "text" => Content::Text(TextContent {
            text: content.text.clone(),
        }),
        "thinking" => Content::Thinking(ThinkingContent {
            thinking: content.thinking.clone(),
            thinking_signature: content.signature.clone(),
            signature_type: content.signature_type.clone(),
            redacted: content.redacted,
        }),
        "tool_call" => Content::ToolCall(to_tool_call(
            content.tool_call.as_ref().expect("tool_call content"),
        )),
        other => panic!("unknown content kind {other}"),
    }
}

fn to_tool_call(call: &FixtureToolCall) -> ToolCall {
    ToolCall {
        id: call.id.clone(),
        name: call.name.clone(),
        arguments: call.arguments.clone(),
        custom: call.custom,
    }
}

fn stop_reason(raw: &str) -> Option<StopReason> {
    match raw {
        "" => None,
        "pending" => Some(StopReason::Pending),
        "stop" => Some(StopReason::Stop),
        "stopSequence" => Some(StopReason::StopSequence),
        "length" => Some(StopReason::Length),
        "toolUse" => Some(StopReason::ToolUse),
        "contentFilter" => Some(StopReason::ContentFilter),
        "error" => Some(StopReason::Error),
        "aborted" => Some(StopReason::Aborted),
        other => panic!("unknown stop reason {other}"),
    }
}

fn event_type(raw: &str) -> Option<ResponseEventType> {
    match raw {
        "start" => Some(ResponseEventType::Start),
        "text_start" => Some(ResponseEventType::TextStart),
        "text_delta" => Some(ResponseEventType::TextDelta),
        "text_end" => Some(ResponseEventType::TextEnd),
        "thinking_start" => Some(ResponseEventType::ThinkingStart),
        "thinking_delta" => Some(ResponseEventType::ThinkingDelta),
        "thinking_end" => Some(ResponseEventType::ThinkingEnd),
        "thinking_signature" => Some(ResponseEventType::ThinkingSignature),
        "toolcall_start" => Some(ResponseEventType::ToolCallStart),
        "toolcall_delta" => Some(ResponseEventType::ToolCallDelta),
        "toolcall_end" => Some(ResponseEventType::ToolCallEnd),
        "done" => Some(ResponseEventType::Done),
        "error" => Some(ResponseEventType::Error),
        // Go's Type is a free string; the Rust enum is closed, so unknown
        // wire values are unrepresentable rather than runtime-rejected.
        _ => None,
    }
}

fn to_message(message: &FixtureMessage) -> AssistantMessage {
    AssistantMessage {
        content: message.content.iter().map(to_content).collect(),
        api: message.api.clone(),
        provider: message.provider.clone(),
        model: message.model.clone(),
        response_model: message.response_model.clone(),
        response_id: message.response_id.clone(),
        output_id: message.output_id.clone(),
        upstream_request_id: message.upstream_request_id.clone(),
        diagnostics: Vec::new(),
        usage: message
            .usage
            .as_ref()
            .map_or_else(Usage::default, |usage| Usage {
                input: usage.input,
                output: usage.output,
                cache_read: usage.cache_read,
                cache_write: usage.cache_write,
                reasoning: usage.reasoning,
                total_tokens: usage.total_tokens,
            }),
        stop_reason: stop_reason(&message.stop_reason),
        stop_sequence: message.stop_sequence.clone(),
        error_message: message.error_message.clone(),
        failure: None,
        debug_ref: message.debug_ref.clone(),
        timestamp_ms: message.timestamp_ms,
    }
}

fn to_event(event: &FixtureEvent) -> Option<ResponseEvent> {
    Some(ResponseEvent {
        kind: event_type(&event.kind)?,
        content_index: event.content_index,
        delta: event.delta.clone(),
        content: event.content.clone(),
        partial: event.partial.as_ref().map(|m| Arc::new(to_message(m))),
        tool_call_id: event.tool_call_id.clone(),
        tool_name: event.tool_name.clone(),
        tool_call: event.tool_call.as_ref().map(to_tool_call),
        reason: stop_reason(&event.reason),
        message: event.message.as_ref().map(to_message),
        error: event.error.as_ref().map(to_message),
    })
}

fn to_failure(failure: &FixtureFailure) -> Failure {
    Failure {
        code: failure.code.clone(),
        message: failure.message.clone(),
        cause: None,
        local_gate: failure.local_gate,
        upstream_fault: failure.upstream_fault,
        retry_after_seconds: failure.retry_after_seconds,
        retry_after_minute: failure.retry_after_minute,
        context_length: failure.context_length,
        rate_limited: failure.rate_limited,
        canceled: failure.canceled,
        timeout: failure.timeout,
        client_fixable: failure.client_fixable,
        trace_id: failure.trace_id.clone(),
        reset_hint: failure.reset_hint,
    }
}

fn protocol_for(name: &str) -> Box<dyn ProtocolEncoder> {
    match name {
        "responses" => Box::new(ResponsesProtocol),
        "chat" => Box::new(ChatProtocol),
        "messages" => Box::new(AnthropicProtocol),
        other => panic!("unknown protocol {other}"),
    }
}

// ---------------------------------------------------------------------------
// Case runner + canonicalized comparison
// ---------------------------------------------------------------------------

struct ActualCase {
    sse: Vec<SseEvent>,
    json: Option<Vec<u8>>,
    encode_error: Option<String>,
    /// The event kind Go rejected but Rust's closed enum cannot represent.
    unrepresentable: bool,
}

fn run_case(case: &FixtureCase) -> ActualCase {
    let protocol = protocol_for(&case.protocol);
    let mut actual = ActualCase {
        sse: Vec::new(),
        json: None,
        encode_error: None,
        unrepresentable: false,
    };
    match case.mode.as_str() {
        "stream" => {
            let mut encoder = protocol.new_stream_encoder(&case.model, case.include_usage);
            for event in &case.events {
                let Some(event) = to_event(event) else {
                    actual.unrepresentable = true;
                    actual.encode_error = Some("<unrepresentable event type>".to_string());
                    break;
                };
                match encoder.encode(&event) {
                    Ok(batch) => actual.sse.extend(batch),
                    Err(err) => {
                        actual.encode_error = Some(err.to_string());
                        break;
                    }
                }
            }
        }
        "final" => match protocol
            .encode_final(case.message.as_ref().map(to_message).as_ref(), &case.model)
        {
            Ok(body) => actual.json = Some(body),
            Err(err) => actual.encode_error = Some(err.to_string()),
        },
        "error" => {
            let failure = to_failure(case.error.as_ref().expect("error case"));
            actual.json = Some(protocol.encode_error(&failure, &case.debug_ref));
        }
        "http_error" => {
            let http = case.http_error.as_ref().expect("http_error case");
            actual.json = Some(protocol.encode_http_error(&HttpError {
                failure: devin2api::domain::classify(&to_failure(&http.failure)),
                client_fixable: http.client_fixable,
                stage: http.stage.clone(),
                debug_ref: http.debug_ref.clone(),
            }));
        }
        other => panic!("unknown mode {other}"),
    }
    actual
}

fn rules() -> CanonRules {
    let mut rules = CanonRules::default();
    rules.timestamp_keys.push("completed_at".to_string());
    rules
}

/// Canonicalizes one case's `SSE` data payloads as a single `JSON` array so
/// generated ids map to `<id#N>` consistently across all events of the case.
fn canon_sse(events: &[ExpectedSse], rules: &CanonRules) -> Value {
    let data: Vec<Value> = events
        .iter()
        .map(|event| {
            serde_json::from_str(&event.data).unwrap_or_else(|_| Value::String(event.data.clone()))
        })
        .collect();
    canonicalize_json(&Value::Array(data), rules)
}

fn canon_sse_actual(events: &[SseEvent], rules: &CanonRules) -> Value {
    let data: Vec<Value> = events
        .iter()
        .map(|event| {
            let text = String::from_utf8_lossy(&event.data);
            serde_json::from_str(&text).unwrap_or_else(|_| Value::String(text.into_owned()))
        })
        .collect();
    canonicalize_json(&Value::Array(data), rules)
}

fn canon_body(raw: &str, rules: &CanonRules) -> Value {
    let value: Value = serde_json::from_str(raw.trim_end()).expect("expected body is JSON");
    canonicalize_json(&value, rules)
}

fn assert_case_parity(case_name: &str) -> (FixtureCase, ExpectedCase, ActualCase) {
    let cases = load_cases();
    let expected = load_expected();
    let case = cases
        .into_iter()
        .find(|case| case.name == case_name)
        .unwrap_or_else(|| panic!("fixture case {case_name}"));
    let expected = expected
        .into_iter()
        .find(|case| case.name == case_name)
        .unwrap_or_else(|| panic!("expected case {case_name}"));
    let actual = run_case(&case);

    // Encode-error agreement: both sides error or neither does. Go's
    // "unknown" event type is unrepresentable in Rust's closed enum — the
    // fixture asserts Go rejected it; the Rust side is a compile-time
    // guarantee documented by `unrepresentable`.
    match (&expected.encode_error, &actual.encode_error) {
        (Some(_), Some(_)) | (None, None) => {}
        (want, got) => panic!("{case_name}: encode_error mismatch: expected {want:?}, got {got:?}"),
    }
    if expected.encode_error.is_some() && !actual.unrepresentable {
        assert_eq!(
            expected.encode_error.as_deref(),
            actual.encode_error.as_deref(),
            "{case_name}: encode error text"
        );
    }

    let rules = rules();
    let expected_names: Vec<&str> = expected
        .sse
        .iter()
        .map(|event| event.name.as_str())
        .collect();
    let actual_names: Vec<&str> = actual.sse.iter().map(|event| event.name).collect();
    assert_eq!(
        expected_names, actual_names,
        "{case_name}: SSE event name sequence"
    );
    let expected_data = canon_sse(&expected.sse, &rules);
    let actual_data = canon_sse_actual(&actual.sse, &rules);
    assert_eq!(
        expected_data, actual_data,
        "{case_name}: SSE data payloads (canonicalized)"
    );

    match (&expected.json, &actual.json) {
        (Some(expected), Some(actual)) => {
            let actual_text = String::from_utf8(actual.clone()).expect("actual body utf8");
            assert_eq!(
                canon_body(expected, &rules),
                canon_body(&actual_text, &rules),
                "{case_name}: JSON body (canonicalized)"
            );
        }
        (None, None) => {}
        (want, got) => panic!("{case_name}: json presence mismatch: {want:?} vs {got:?}"),
    }
    (case, expected, actual)
}

fn sse_data(actual: &ActualCase, index: usize) -> Value {
    serde_json::from_slice(&actual.sse[index].data).expect("sse data is JSON")
}

// ---------------------------------------------------------------------------
// common/error_test.go — error type/status/code mapping tables
// ---------------------------------------------------------------------------

/// `G/internal/api/common/error_test.go` `TestOpenAIErrorType`.
#[test]
fn openai_error_type_table() {
    let cases = [
        (
            "invalid_argument: model does not support image",
            "invalid_request_error",
        ),
        (
            "resource_exhausted: rate limit exceeded",
            "rate_limit_error",
        ),
        ("permission_denied: not allowed", "invalid_request_error"),
        ("not_found: model missing", "not_found_error"),
        ("unavailable: upstream offline", "server_error"),
        ("some unknown error", "server_error"),
        // Upstream internal faults stuffed into fixable codes stay
        // server_error — the blame is upstream's.
        (
            "invalid_argument: an internal error occurred (trace ID: abc)",
            "server_error",
        ),
    ];
    for (message, want) in cases {
        let failure = devin2api::domain::classify_text(message);
        assert_eq!(
            openai_error_type(&failure),
            want,
            "OpenAIErrorType({message:?})"
        );
    }
}

/// `G/internal/api/common/error_test.go` `TestAnthropicErrorType`.
#[test]
fn anthropic_error_type_table() {
    let cases = [
        ("invalid_argument: bad request", "invalid_request_error"),
        (
            "resource_exhausted: rate limit exceeded",
            "rate_limit_error",
        ),
        ("permission_denied: not allowed", "invalid_request_error"),
        ("not_found: model missing", "not_found_error"),
        ("unavailable: upstream offline", "api_error"),
        ("some unknown error", "api_error"),
        (
            "permission_denied: an internal error occurred (trace ID: abc)",
            "api_error",
        ),
    ];
    for (message, want) in cases {
        let failure = devin2api::domain::classify_text(message);
        assert_eq!(
            anthropic_error_type(&failure),
            want,
            "AnthropicErrorType({message:?})"
        );
    }
}

/// `G/internal/api/common/error_test.go` `TestHTTPStatus`.
#[test]
fn http_status_table() {
    let cases = [
        ("permission_denied: blocked by content policy", 400),
        (
            "invalid_argument: The prompt is too long for this model",
            413,
        ),
        ("invalid_argument: internal error", 400),
        ("unauthenticated: bad token", 401),
        ("not_found: model missing", 404),
        ("resource_exhausted: quota", 429),
        ("unavailable: TLS handshake timeout", 502),
        ("stream disconnected", 502),
        (
            "invalid_argument: an internal error occurred (trace ID: abc)",
            502,
        ),
        (
            "invalid_argument: protocol error: incomplete envelope: read: connection reset by peer",
            502,
        ),
    ];
    for (message, want) in cases {
        let failure = devin2api::domain::classify_text(message);
        assert_eq!(http_status(&failure), want, "HTTPStatus({message:?})");
    }
}

/// `G/internal/api/common/error_test.go` `TestErrorCode`.
#[test]
fn error_code_table() {
    let failure =
        devin2api::domain::classify_text("invalid_argument: The prompt is too long for this model");
    assert_eq!(error_code(&failure), json!("context_length_exceeded"));
    let failure = devin2api::domain::classify_text("permission_denied: blocked");
    assert_eq!(error_code(&failure), Value::Null);
}

// ---------------------------------------------------------------------------
// responses/response_test.go
// ---------------------------------------------------------------------------

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderEncodesReasoningAndToolItems`.
#[test]
fn stream_encoder_encodes_reasoning_and_tool_items() {
    let (_case, expected, actual) = assert_case_parity("responses_stream_reasoning_and_tool_items");
    // Go asserts resp_/rs_/fc_ prefixes on generated ids; canonicalization
    // already proved cross-side equality, so check the Rust side's shape.
    let created = sse_data(&actual, 0);
    assert!(
        created["response"]["id"]
            .as_str()
            .is_some_and(|id| id.starts_with("resp_")),
        "response id prefix"
    );
    let reasoning_added = sse_data(&actual, 2);
    let reasoning_id = reasoning_added["item"]["id"].as_str().unwrap();
    assert!(reasoning_id.starts_with("rs_"), "reasoning id prefix");
    assert_eq!(sse_data(&actual, 4)["item_id"], json!(reasoning_id));
    let tool_added = sse_data(&actual, 8);
    let tool_item_id = tool_added["item"]["id"].as_str().unwrap();
    assert!(tool_item_id.starts_with("fc_") && tool_item_id != "call-1");
    assert_eq!(tool_added["item"]["call_id"], json!("call-1"));
    assert_eq!(sse_data(&actual, 9)["item_id"], json!(tool_item_id));
    let completed = sse_data(&actual, actual.sse.len() - 1);
    assert_eq!(completed["response"]["id"], created["response"]["id"]);
    let output = completed["response"]["output"].as_array().unwrap();
    assert_eq!(output.len(), 2);
    assert_eq!(output[0]["type"], json!("reasoning"));
    assert_eq!(output[1]["type"], json!("function_call"));
    assert_eq!(output[1]["call_id"], json!("call-1"));
    // sequence_number is a dense 0..n counter across the whole stream.
    for (index, event) in actual.sse.iter().enumerate() {
        let data: Value = serde_json::from_slice(&event.data).unwrap();
        assert_eq!(data["sequence_number"], json!(index), "event[{index}]");
    }
    assert_eq!(expected.sse.len(), actual.sse.len());
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderEncodesFinalTextMessage`.
#[test]
fn stream_encoder_encodes_final_text_message() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_final_text_message");
    let item_added = sse_data(&actual, 2);
    let message_id = item_added["item"]["id"].as_str().unwrap();
    assert!(message_id.starts_with("msg_"), "message id prefix");
    let part_added = sse_data(&actual, 3);
    assert_eq!(part_added["item_id"], json!(message_id));
    assert_eq!(part_added["content_index"], json!(0));
    let completed = sse_data(&actual, actual.sse.len() - 1);
    let message = &completed["response"]["output"][0];
    assert_eq!(message["type"], json!("message"));
    assert_eq!(message["content"][0]["text"], json!("final answer"));
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderHoldsReasoningForLateSignature`.
#[test]
fn stream_encoder_holds_reasoning_for_late_signature() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_late_signature");
    let reasoning_done = sse_data(&actual, 11);
    assert_eq!(reasoning_done["item"]["encrypted_content"], json!("sig"));
    let completed = sse_data(&actual, actual.sse.len() - 1);
    assert_eq!(
        completed["response"]["output"][0]["encrypted_content"],
        json!("sig")
    );
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderAccumulatesSignatureFragments`.
#[test]
fn stream_encoder_accumulates_signature_fragments() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_signature_fragments");
    let done = sse_data(&actual, 7);
    assert_eq!(done["item"]["encrypted_content"], json!("AAABBB"));
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderEncodesSignatureOnlyReasoning`.
#[test]
fn stream_encoder_encodes_signature_only_reasoning() {
    let (_case, _expected, actual) =
        assert_case_parity("responses_stream_signature_only_reasoning");
    let completed = sse_data(&actual, actual.sse.len() - 1);
    assert_eq!(
        completed["response"]["output"][0]["encrypted_content"],
        json!("sig")
    );
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderRejectsUnknownEvent`. Go's `Type` is a free string; the
/// Rust `ResponseEventType` enum is closed, so an unknown kind is
/// unrepresentable — the fixture asserts the Go side rejected it.
#[test]
fn stream_encoder_rejects_unknown_event() {
    let (_case, expected, actual) = assert_case_parity("responses_stream_rejects_unknown_event");
    assert!(expected.encode_error.is_some());
    assert!(actual.unrepresentable);
    // The encoder still refuses events that fail validation.
    let mut encoder = dispatch::ResponsesProtocol.new_stream_encoder("gpt-test", false);
    let invalid = ResponseEvent {
        kind: ResponseEventType::TextDelta,
        content_index: 0,
        ..ResponseEvent::default()
    };
    assert!(encoder.encode(&invalid).is_err());
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderRejectsDoneWithOpenItem`.
#[test]
fn stream_encoder_rejects_done_with_open_item() {
    let (_case, _expected, actual) =
        assert_case_parity("responses_stream_rejects_done_with_open_item");
    assert!(
        actual
            .encode_error
            .as_deref()
            .is_some_and(|err| err.contains("open message item")),
        "done error = {:?}",
        actual.encode_error
    );
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderEncodesLengthAsIncomplete`.
#[test]
fn stream_encoder_encodes_length_as_incomplete() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_length_incomplete");
    let names: Vec<&str> = actual.sse.iter().map(|event| event.name).collect();
    assert_eq!(
        names,
        [
            "response.created",
            "response.in_progress",
            "response.incomplete"
        ]
    );
    let response = &sse_data(&actual, 2)["response"];
    assert_eq!(response["status"], json!("incomplete"));
    assert!(response.get("completed_at").is_none_or(Value::is_null));
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestResponseUsageIncludesCachedTokensInInputTotal` (via `encode_response`).
#[test]
fn response_usage_includes_cached_tokens_in_input_total() {
    let (_case, _expected, actual) = assert_case_parity("responses_final_cached_usage");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    let usage = &body["usage"];
    assert_eq!(usage["input_tokens"], json!(12362));
    assert_eq!(usage["input_tokens_details"]["cached_tokens"], json!(12195));
    assert_eq!(usage["output_tokens"], json!(61));
    assert_eq!(usage["total_tokens"], json!(12423));
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderOpenAISignatureRestoresItemID`.
#[test]
fn stream_encoder_openai_signature_restores_item_id() {
    let (_case, _expected, actual) =
        assert_case_parity("responses_stream_openai_signature_item_id");
    let added = sse_data(&actual, 2);
    assert_eq!(added["item"]["id"], json!("rs_real1"));
    assert_eq!(
        added["item"]["encrypted_content"],
        json!(
            "[{\"id\":\"rs_real1\",\"type\":\"reasoning\",\"encrypted_content\":\"gAAA\",\"summary\":[],\"content\":[],\"status\":\"\"}]"
        )
    );
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderMessageItemUsesOutputID`.
#[test]
fn stream_encoder_message_item_uses_output_id() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_message_item_output_id");
    let added = sse_data(&actual, 2);
    assert_eq!(added["item"]["id"], json!("msg_up1"));
}

/// `G/internal/api/`openai`/responses/response_test.go`
/// `TestStreamEncoderCustomToolCall`.
#[test]
fn stream_encoder_custom_tool_call() {
    let (_case, _expected, actual) = assert_case_parity("responses_stream_custom_tool_call");
    let added = sse_data(&actual, 2);
    assert_eq!(added["item"]["type"], json!("custom_tool_call"));
    assert_eq!(
        sse_data(&actual, 3)["type"],
        json!("response.custom_tool_call_input.delta")
    );
    let done = sse_data(&actual, 5);
    assert_eq!(done["item"]["input"], json!("*** Begin Patch"));
    assert!(done["item"].get("arguments").is_none());
}

/// QA scenario `failure_and_partial_tool_stream`: a mid-stream failure
/// after a partial tool call must end in a real `response.failed` frame,
/// not a fabricated completion.
#[test]
fn failure_and_partial_tool_stream_responses() {
    let (_case, _expected, actual) =
        assert_case_parity("responses_stream_failure_after_partial_tool");
    let last = actual.sse.last().unwrap();
    assert_eq!(last.name, "response.failed");
    let data = sse_data(&actual, actual.sse.len() - 1);
    assert_eq!(data["response"]["status"], json!("failed"));
    assert_eq!(data["error"]["type"], json!("rate_limit_error"));
}

// ---------------------------------------------------------------------------
// chat/response_test.go
// ---------------------------------------------------------------------------

/// `G/internal/api/`openai`/chat/response_test.go` `TestStreamEncoderEmitsRoleAndText`.
#[test]
fn stream_encoder_emits_role_and_text() {
    let (_case, _expected, actual) = assert_case_parity("chat_stream_role_and_text");
    assert_eq!(actual.sse.len(), 5); // role, "final ", "answer", finish, [DONE]
    let first = sse_data(&actual, 0);
    assert_eq!(first["choices"][0]["delta"]["role"], json!("assistant"));
    let raw = String::from_utf8(actual.sse[0].data.clone()).unwrap();
    assert!(
        !raw.contains("\"content\":"),
        "first chunk must not carry content"
    );
    assert_eq!(
        sse_data(&actual, 1)["choices"][0]["delta"]["content"],
        json!("final ")
    );
}

/// `G/internal/api/`openai`/chat/response_test.go` `TestStreamEncoderEmitsToolCalls`.
#[test]
fn stream_encoder_emits_tool_calls() {
    let (_case, _expected, actual) = assert_case_parity("chat_stream_tool_calls");
    assert_eq!(actual.sse.len(), 6);
    let tool_call = &sse_data(&actual, 1)["choices"][0]["delta"]["tool_calls"][0];
    assert_eq!(tool_call["function"]["name"], json!("lookup"));
}

/// `G/internal/api/`openai`/chat/response_test.go`
/// `TestStreamEncoderToolCallAfterOtherBlocks` — rekeyed `tool_call_id` deltas
/// must still land on the right tool, addressed by content index.
#[test]
fn stream_encoder_tool_call_after_other_blocks() {
    let (_case, _expected, actual) = assert_case_parity("chat_stream_tool_call_after_other_blocks");
    assert_eq!(actual.sse.len(), 6);
    let tool_call = &sse_data(&actual, 2)["choices"][0]["delta"]["tool_calls"][0];
    assert_eq!(tool_call["index"], json!(0));
    assert_eq!(tool_call["function"]["arguments"], json!("{\"city\":\""));
}

/// `G/internal/api/`openai`/chat/response_test.go` `TestEncodeResponseFinal`.
#[test]
fn encode_response_final() {
    let (_case, _expected, actual) = assert_case_parity("chat_final");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    assert_eq!(body["object"], json!("chat.completion"));
    assert_eq!(body["model"], json!("gpt-test"));
    assert_eq!(
        body["usage"]["prompt_tokens_details"]["cached_tokens"],
        json!(3)
    );
}

/// `G/internal/api/`openai`/chat/response_test.go`
/// `TestEncodeResponseFinalWithReasoning`.
#[test]
fn encode_response_final_with_reasoning() {
    let (_case, _expected, actual) = assert_case_parity("chat_final_with_reasoning");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    let message = &body["choices"][0]["message"];
    assert_eq!(message["content"], json!("hello"));
    assert_eq!(message["reasoning_content"], json!("think"));
}

/// `G/internal/api/`openai`/chat/response_test.go`
/// `TestMessageToChatKeepsTextWithToolCalls` (via `encode_response`).
#[test]
fn message_to_chat_keeps_text_with_tool_calls() {
    let (_case, _expected, actual) = assert_case_parity("chat_final_text_with_tool_calls");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    let message = &body["choices"][0]["message"];
    assert_eq!(message["content"], json!("let me check"));
    assert_eq!(message["tool_calls"].as_array().unwrap().len(), 1);

    let (_case, _expected, actual) = assert_case_parity("chat_final_tool_call_only");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    assert_eq!(body["choices"][0]["message"]["content"], Value::Null);
}

/// `G/internal/api/`openai`/chat/response_test.go` `TestStreamEncoderEmitsError`.
#[test]
fn stream_encoder_emits_error() {
    let (_case, _expected, actual) = assert_case_parity("chat_stream_error");
    assert_eq!(actual.sse.len(), 2);
    assert_eq!(actual.sse[0].name, "");
    assert_eq!(actual.sse[1].name, common::SSE_DONE);
    let data = sse_data(&actual, 0);
    assert_eq!(data["object"], json!("chat.completion.chunk"));
    assert_eq!(data["choices"].as_array().unwrap().len(), 0);
    assert_eq!(
        data["error"]["message"],
        json!("resource_exhausted: rate limit exceeded")
    );
    assert_eq!(data["error"]["type"], json!("rate_limit_error"));

    // Encoding after the error must fail — the stream is done.
    let mut encoder = dispatch::ChatProtocol.new_stream_encoder("gpt-test", false);
    let failed = AssistantMessage {
        provider: "devin".to_string(),
        stop_reason: Some(StopReason::Error),
        error_message: "resource_exhausted: rate limit exceeded".to_string(),
        ..AssistantMessage::default()
    };
    let event = ResponseEvent {
        kind: ResponseEventType::Error,
        reason: Some(StopReason::Error),
        error: Some(failed),
        ..ResponseEvent::default()
    };
    assert!(encoder.encode(&event).is_ok());
    assert!(
        encoder.encode(&event).is_err(),
        "encode after error must fail"
    );
}

/// `G/internal/api/`openai`/chat/response_test.go`
/// `TestStreamEncoderEmitsThinkingAsReasoningContent`.
#[test]
fn stream_encoder_emits_thinking_as_reasoning_content() {
    let (_case, _expected, actual) =
        assert_case_parity("chat_stream_thinking_as_reasoning_content");
    assert_eq!(actual.sse.len(), 5);
    assert_eq!(
        sse_data(&actual, 1)["choices"][0]["delta"]["reasoning_content"],
        json!("think")
    );
    assert_eq!(
        sse_data(&actual, 2)["choices"][0]["delta"]["content"],
        json!("hello")
    );
}

/// `include_usage` streams a usage-only chunk before [DONE].
#[test]
fn stream_encoder_include_usage() {
    let (_case, _expected, actual) = assert_case_parity("chat_stream_include_usage");
    assert_eq!(actual.sse.len(), 5);
    let usage_chunk = sse_data(&actual, 3);
    assert_eq!(usage_chunk["choices"].as_array().unwrap().len(), 0);
    assert_eq!(usage_chunk["usage"]["prompt_tokens"], json!(10));
    assert_eq!(actual.sse[4].name, common::SSE_DONE);
}

// ---------------------------------------------------------------------------
// messages/response_test.go
// ---------------------------------------------------------------------------

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderEmitsMessageStartAndText`.
#[test]
fn stream_encoder_emits_message_start_and_text() {
    let (_case, _expected, actual) = assert_case_parity("messages_stream_message_start_and_text");
    assert_eq!(actual.sse.len(), 6);
    assert_eq!(actual.sse[0].name, "message_start");
    assert_eq!(actual.sse[5].name, "message_stop");
}

/// `G/internal/api/anthropic/messages/response_test.go` `TestStreamEncoderEmitsToolUse`.
#[test]
fn stream_encoder_emits_tool_use() {
    let (_case, _expected, actual) = assert_case_parity("messages_stream_tool_use");
    assert_eq!(actual.sse.len(), 7);
    assert_eq!(actual.sse[0].name, "message_start");
    assert_eq!(actual.sse[6].name, "message_stop");
    let start_block = sse_data(&actual, 1);
    assert_eq!(start_block["content_block"]["type"], json!("tool_use"));
    assert_eq!(start_block["content_block"]["name"], json!("lookup"));
    assert_eq!(sse_data(&actual, 4)["type"], json!("content_block_stop"));
}

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderHoldsThinkingForLateSignature`.
#[test]
fn stream_encoder_holds_thinking_for_late_signature() {
    let (_case, _expected, actual) = assert_case_parity("messages_stream_late_signature");
    let names: Vec<&str> = actual.sse.iter().map(|event| event.name).collect();
    assert_eq!(
        names,
        [
            "message_start",
            "content_block_start",
            "content_block_delta",
            "content_block_start",
            "content_block_delta",
            "content_block_delta",
            "content_block_stop",
            "content_block_stop",
            "message_delta",
            "message_stop",
        ]
    );
    let signature_delta = sse_data(&actual, 5);
    assert_eq!(signature_delta["delta"]["type"], json!("signature_delta"));
    assert_eq!(signature_delta["delta"]["signature"], json!("sig"));
    assert_eq!(signature_delta["index"], json!(0));
    let thinking_stop = sse_data(&actual, 6);
    assert_eq!(thinking_stop["index"], json!(0));
    assert!(
        thinking_stop
            .get("content_block")
            .is_none_or(Value::is_null)
    );
    let tool_stop = sse_data(&actual, 7);
    assert_eq!(tool_stop["index"], json!(1));
}

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderClosesBlocksInIndexOrder`.
#[test]
fn stream_encoder_closes_blocks_in_index_order() {
    let (_case, _expected, actual) =
        assert_case_parity("messages_stream_closes_blocks_in_index_order");
    let stops: Vec<i64> = actual
        .sse
        .iter()
        .filter_map(|event| {
            let data: Value = serde_json::from_slice(&event.data).unwrap();
            (data["type"] == json!("content_block_stop")).then(|| data["index"].as_i64().unwrap())
        })
        .collect();
    assert_eq!(stops, [0, 1]);
}

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderBuffersSignatureFragments`.
#[test]
fn stream_encoder_buffers_signature_fragments() {
    let (_case, _expected, actual) = assert_case_parity("messages_stream_signature_fragments");
    let signatures: Vec<String> = actual
        .sse
        .iter()
        .filter_map(|event| {
            let data: Value = serde_json::from_slice(&event.data).unwrap();
            let delta = &data["delta"];
            (delta["type"] == json!("signature_delta"))
                .then(|| delta["signature"].as_str().unwrap().to_string())
        })
        .collect();
    assert_eq!(signatures, ["AAABBB"]);
}

/// `G/internal/api/anthropic/messages/response_test.go` `TestEncodeResponseFinal`.
#[test]
fn messages_encode_response_final() {
    let (_case, _expected, actual) = assert_case_parity("messages_final");
    let body: Value = serde_json::from_slice(&actual.json.unwrap()).unwrap();
    assert_eq!(body["type"], json!("message"));
    assert_eq!(body["model"], json!("claude-test"));
    assert_eq!(body["usage"]["cache_read_input_tokens"], json!(3));
    assert_eq!(body["usage"]["cache_creation_input_tokens"], json!(2));
}

/// `G/internal/api/anthropic/messages/response_test.go` `TestStreamEncoderEmitsError`.
#[test]
fn messages_stream_encoder_emits_error() {
    let (_case, _expected, actual) = assert_case_parity("messages_stream_error");
    assert_eq!(actual.sse.len(), 1);
    assert_eq!(actual.sse[0].name, "error");
    let data = sse_data(&actual, 0);
    assert_eq!(data["type"], json!("error"));
    assert_eq!(
        data["error"]["message"],
        json!("permission_denied: not allowed")
    );
    assert_eq!(data["error"]["type"], json!("invalid_request_error"));

    let mut encoder = dispatch::AnthropicProtocol.new_stream_encoder("claude-test", false);
    let failed = AssistantMessage {
        provider: "devin".to_string(),
        stop_reason: Some(StopReason::Error),
        error_message: "permission_denied: not allowed".to_string(),
        ..AssistantMessage::default()
    };
    let event = ResponseEvent {
        kind: ResponseEventType::Error,
        reason: Some(StopReason::Error),
        error: Some(failed),
        ..ResponseEvent::default()
    };
    assert!(encoder.encode(&event).is_ok());
    assert!(
        encoder.encode(&event).is_err(),
        "encode after error must fail"
    );
}

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderSignatureReadyAtThinkingEnd`.
#[test]
fn stream_encoder_signature_ready_at_thinking_end() {
    let (_case, _expected, actual) =
        assert_case_parity("messages_stream_signature_ready_at_thinking_end");
    assert_eq!(actual.sse.len(), 5);
    assert_eq!(actual.sse[3].name, "content_block_delta");
    assert_eq!(actual.sse[4].name, "content_block_stop");
    let delta = &sse_data(&actual, 3)["delta"];
    assert_eq!(delta["type"], json!("signature_delta"));
    assert_eq!(delta["signature"], json!("sig"));
}

/// `G/internal/api/anthropic/messages/response_test.go`
/// `TestStreamEncoderRedactedThinkingDeferredStart`.
#[test]
fn stream_encoder_redacted_thinking_deferred_start() {
    let (_case, _expected, actual) =
        assert_case_parity("messages_stream_redacted_thinking_deferred_start");
    assert_eq!(actual.sse.len(), 3);
    let start = sse_data(&actual, 1);
    assert_eq!(start["type"], json!("content_block_start"));
    assert_eq!(start["content_block"]["type"], json!("redacted_thinking"));
    assert_eq!(start["content_block"]["data"], json!("sealed-payload"));
    let stop = sse_data(&actual, 2);
    assert_eq!(stop["type"], json!("content_block_stop"));
    assert!(stop.get("content_block").is_none_or(Value::is_null));
}

/// QA scenario `failure_and_partial_tool_stream`: a mid-stream failure
/// after a partial tool call must end in a real `error` frame, not a
/// fabricated completion.
#[test]
fn failure_and_partial_tool_stream_messages() {
    let (_case, _expected, actual) =
        assert_case_parity("messages_stream_failure_after_partial_tool");
    let last = actual.sse.last().unwrap();
    assert_eq!(last.name, "error");
    let data = sse_data(&actual, actual.sse.len() - 1);
    assert_eq!(data["type"], json!("error"));
    assert_eq!(data["error"]["type"], json!("rate_limit_error"));
}

// ---------------------------------------------------------------------------
// dispatch layer — encode_error / encode_http_error / append_sse
// ---------------------------------------------------------------------------

/// `G/internal/app/protocols.go` `EncodeError` bodies per protocol.
#[test]
fn protocol_encode_error_bodies() {
    assert_case_parity("responses_encode_error_rate_limit");
    assert_case_parity("chat_encode_error_internal");
    assert_case_parity("messages_encode_error_permission");
}

/// `G/internal/app/protocols.go` `EncodeHTTPError` bodies per protocol.
#[test]
fn protocol_encode_http_error_bodies() {
    assert_case_parity("responses_http_error_rate_limit");
    assert_case_parity("chat_http_error_client_fixable");
    assert_case_parity("messages_http_error_upstream");
    assert_case_parity("messages_http_error_client_fixable");
}

/// `G/internal/app/protocols.go` `AppendSSE` framing: named `event:`/`data:`
/// pairs for responses/messages, data-only plus `[DONE]` for chat.
#[test]
fn protocol_append_sse_framing() {
    let mut dst = bytes::BytesMut::new();
    ResponsesProtocol.append_sse(&mut dst, "response.created", b"{}");
    assert_eq!(&dst[..], b"event: response.created\ndata: {}\n\n");

    let mut dst = bytes::BytesMut::new();
    AnthropicProtocol.append_sse(&mut dst, "message_stop", b"{\"type\":\"message_stop\"}");
    assert_eq!(
        &dst[..],
        b"event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n"
    );

    let mut dst = bytes::BytesMut::new();
    ChatProtocol.append_sse(&mut dst, "", b"{}");
    ChatProtocol.append_sse(&mut dst, common::SSE_DONE, common::SSE_DONE.as_bytes());
    assert_eq!(&dst[..], b"data: {}\n\ndata: [DONE]\n\n");
}

/// `G/internal/app/protocols.go` `StreamErrorEvents`: only the `OpenAI`-family
/// protocols convert pre-stream failures into in-stream error events.
#[test]
fn protocol_stream_error_events() {
    assert!(ResponsesProtocol.stream_error_events());
    assert!(ChatProtocol.stream_error_events());
    assert!(!AnthropicProtocol.stream_error_events());
}
